[theme]
primaryColor = "#3B82F6"  # Modern blue
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F4F6"  # Subtle gray
textColor = "#262730"
font = "system-ui"  # Modern system font

[ui]
hideTopBar = false

#[browser]
#gatherUsageStats = false


[runner]
fastReruns = true

[client]
showErrorDetails = true
toolbarMode = "minimal"